sudo: false
language: android
before_install:
# https://stackoverflow.com/a/47719835/1275092
- yes | sdkmanager "platforms;android-27"
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-27.0.3
    - android-27
script:
- "./gradlew check jacocoTestReportDebug"
after_success:
- bash <(curl -s https://codecov.io/bash) -f lib/build/reports/jacoco/debug/jacoco.xml